# homepage header
home-name: Abdulhamit Celik


# social links
github: https://github.com/hmtcelik
linkedin: https://www.linkedin.com/in/abdulhamit-celik-07b44722b/
twitter: \#
mail: abhmtcelik@gmail.com